### ISSUE TITLE
model_params.h5py

### ISSUE THREAD

**Issue by BIOVPEPPER** [styvesg/nsd#1]
Hi,
  Not sure if you can see this but can you plz share the model_params.h5py?

**Comment by styvesg** [comment]
I did not share this on github due to the large file size and multiple variants. The file can be regenerated by running the code on NSD.

**Comment by BIOVPEPPER** [comment]
Hi,
 Thanks for responding, but running the code you mean running the code in this repo or you have some publicly encoding model code avaliable code in  the original NSD code avaliability? I contacted Prof.Kendrick but looks like those code are not publicly viewable.

**Comment by styvesg** [comment]
This repo only serves to illustrate the details of this particular model and method. No input data or final parameters were provided. To run this code again you need to download the separate publicly available NSD dataset and adapt this code to run it.

**Comment by gegen666** [comment]
Hi, when i download the data from this link https://s3.console.aws.amazon.com/s3/buckets/natural-scenes-dataset, such as nsddata/experiments/nsdsynthetic/nsdsynthetic_expdesign.mat, it told me that i have no right to download it, it shown as a xml file, as follow:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>EW0HWXPQRKN8FBG2</RequestId>
<HostId>
MFkIiuJj/DUysysBVSJfCBVbk1i9hD6C8S5VInmDKu+ZxYbGaNhy+TWxjMvgBzWoNTxWW2x/6qA=
</HostId>
</Error>
```

but i think nsdsynthetic_expdesign.mat is necessary to run the code 'data_preparation'
so how should I deal with this problem?
thank you @styvesg

**Comment by styvesg** [comment]
While NSDsynthetic is referred to in data_preparation, it is not central to the analysis. You can just not run that part. My understanding though is that this part of NSD which was initially held up (NSDsynthetic) should now have been released. It may still be in a limbo state though. Will check.

**Comment by gegen666** [comment]
Thank you very much for your response, i got what you mean, i will change the data path to the data which i should use, i will try it, thank you again!
